language: android

addons:
  artifacts:
    s3_region: us-east-1

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

jdk: oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew build test